[package]
name = "ez_screenshots"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
screenshots = "0.8.5"
iced = {version = "0.10", features = ["svg", "tokio"]}
tokio = "1.33.0"